language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"

install:
    - pip install nose --use-mirrors
    - pip install mysql-python --use-mirrors
    - pip install psycopg2 --use-mirrors

before_script:
    - mysql -e "grant all on test.* to 'test'@'localhost' identified by 'test';"
    - mysql -e "create database test;"
    - mysql -D test -e 'create schema test_schema;'

    - psql -U postgres -c "create user test password 'test';"
    - psql -U postgres -c "create database test owner test;"
    - PGPASSWORD=test psql -U test -c "create schema test_schema;" test
    - PGPASSWORD=test psql -U test -c "create schema test_schema_2;" test

script:
    - ./sqla_nose.py --dburi=sqlite://
    - ./sqla_nose.py --dburi=mysql://test:test@localhost/test
    - ./sqla_nose.py --dburi=postgresql://test:test@localhost/test
